### ISSUE TITLE
Options to integrate chatbots using Dialogflow

### ISSUE THREAD

**Issue by leslyarun** [chat21/chat21-web-widget#11]
Is it possible to have options to integrate chatbots? Probably I would like to integrate dialogflow api's with chat21. Have a chatbot to answer questions, if the bot is not able to answer, I want to handoff it to a live human agent. I think this would be a great feature for chat21.

**Comment by andrealeo83** [comment]
Tiledesk do it. 
Tiledesk is a customer support platform built on top of Chat21. 
It has Chatbots support and handoff with human agent. It's also OpenSource here https://github.com/tiledesk
See it here : https://www.tiledesk.com

**Comment by andrealeo83** [comment]
you can find DialogFlow Tiledesk integration tutorials here: https://developer.tiledesk.com/apis/tutorials/
