### ISSUE TITLE
[question] setup user to user chat (custom token authentication)

### ISSUE THREAD

**Issue by iutinvg** [chat21/chat21-web-widget#12]
Hello Andrea.

We'd like to try your project to organize chat between users on our website. I got a bit confused about how to set up the widget to allow it. My project is on Django and I'm going to use a custom token to authenticate users in Firebase. I see some functionality related to it in the code (file `auth.service.ts`, function `authenticateFirebaseCustomToken`), but not sure how to create a proper widget configuration.

I have successfully deployed the cloud functions, created groups (using HTTP API) and created a user to user chat on iOS (derived from your demo apps). It's awesome! 

Could you help me to setup the web widget for my use case (user to user chat)? Maybe you have some instructions somewhere or maybe you have some time to give me hints regarding it?

Maybe the right question should be: is it the right piece of software to use for my use case? :)

Thank you for advance!

**Comment by andrealeo83** [comment]
Hi,
At the moment chat21-web-widget is used by our product tiledesk.com. In Tiledesk the site visitors with the widget can chat with the backend agents for customer service. 
If your use case is "User to user chat" you have to extends chat21-web-widget with same features. Example: chat address book, one to one chat (at the moment chat21-web-widget supports only group).

**Comment by iutinvg** [comment]
Hi Andrea,

thank you for answering me!

Group chat is perfect for me. I can create a group every time our business logic dictates. So if the pair of users are allowed to chat, the server will create a group for them (and join these users to the group).

So do you think it's possible to use the widget in this case? If so, will the project-id setting somehow interfere with it? What would be the way to create a proper settings object to configure the widget?

Thank you!

**Comment by iutinvg** [comment]
Andrea, thank you for the link. I think I'll return to you with more questions about the widget. For now, I'll close the issue as I think it's actually irrelevant to your project. 

Thank you once again!
